<?xml version="1.0"?>
<package format="3">
  <name>lifecore_state_msgs</name>
  <version>0.0.0</version>
  <description>ROS 2 interface package for lifecore_state message contracts.</description>
  <maintainer email="7260230+apajon@users.noreply.github.com">Adrien Pajon</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>std_msgs</depend>
  <depend>unique_identifier_msgs</depend>

  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>
</package>
